---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Get Vector version
    ansible.builtin.command: "vector --version"
    changed_when: false
    register: vector_version
  - name: Print Vector version
    ansible.builtin.debug: var=vector_version
  - name: Get Vector Validate Config
    ansible.builtin.command: "vector validate --no-environment --config-yaml /etc/vector/vector.yml"
    changed_when: false
    register: vector_validate