---
# tasks file for vector-role
- name: Install Vector RPM
  ansible.builtin.yum:
    name: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
    state: present
    disable_gpg_check: True
  when: ansible_distribution == "CentOS"
- name: Install Vector DEB
  ansible.builtin.apt:
    deb: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
    state: present
  when: ansible_distribution == "Ubuntu"
- name: Vector templates
  become: true
  ansible.builtin.template:
    src: vector.yml.j2
    dest: "/etc/vector/vector.yml"
    mode: "0755"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
- name: Vector systemd unit
  become: true
  ansible.builtin.template:
    src: vector.service.j2
    dest: "{{systemd_vector}}"
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    backup: true
#  notify: Start Vector service